############################################################
# | AdminSignShop by hexosse                             | #
############################################################

# *---------------- Plugin configuration --------------------*
plugin:
  # Enable metrics
  useMetrics : true
  # Enable updater
  useUpdater : true
  # Download update
  downloadUpdate: true

# *---------------- Shop configuration --------------------*
shop:
  # Path to file containing the worth of each items that
  worthFile: Essentials/worth.yml
  # Factor applied to the worth to get the sell price
  sellFactor: 0.75
  # Factor applied to each level of enchantment
  enchantmentFactor: 0.12
  # Buy shop enable
  buy: true
  # Sell shop enable
  sell: false
  # Default worth value
  defWorth: 0
  # Here are the signs that will be used to create the shop.
  # Those signs MUST exist in SignShop
  signs:
    # Currency symbol you want to use.
    # Might be the same as in essential if using EssentialsEco
    currencySymbol: '$'
    # You can specified the symbol you want to use when creating
    # a buy shop. Look at SignShop configuration.
    # Can be useful when used in another language.
    buy: iBuy
    # You can specified the symbol you want to use when creating
    # a sell shop. Look at SignShop configuration.
    # Can be useful when used in another language.
    sell: iSell
    # line1 and line2 can use one of this property :
    # %quantity% : Quantity,  %name% : unlocalized name
    # %book% : book name (used for enchanted book)
    # %enchanted_item% : name of the item which is enchanted
    # %enchanted_name% : name of the enchantment applied to the item which is enchanted
    # line1: "%quantity% %book% %enchanted_item%"
    # line2: "%name% %enchanted_name%"
    line1: ""
    line2: ""
    line12: "%quantity% %book% %enchanted_item% %name% %enchanted_name%"


# *-------------- GroundItemManager configuration -----------------*
groundItem:
  # Ground item si enable
  groundItem: false


# *-------------- Messages configuration -----------------*
# You can use the default messages provided or translate as you whish.
messages: messages.yml
# Define your localization when using Language Utils plugin.
# Each items will be translated in your Language.
locale: en_US

############################################################