name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.github.hexosse.adminsignshop.AdminSignShop

author: hexosse
website: www.github.hexosse

depend: [SignShop]
softdepend: [GroundItemApi, LangUtils]

commands:
  ass:
    aliases: [adminsignshop, AdminSignShop]
    description: AdminSignShop help Admin server to create SignShop easily.

permissions:
  AdminSignShop.admin: {description: Allows user to modify/destroy other stores and create an Admin Shops, default: false}
  AdminSignShop.*:
    default: op
    children:
        AdminSignShop.admin: true
